// system/components/react/ua-radio/ua-radio.tsx
import { type InputHTMLAttributes, type ReactNode, useId } from 'react'
import type { Size } from '../../../types/tokens'
import '../../styles/ua-radio.scss'

export type RadioMode = 'normal' | 'reverse'

export interface UaRadioProps extends Omit<
  InputHTMLAttributes<HTMLInputElement>,
  'size' | 'type' | 'id'
> {
  size?: Size
  mode?: RadioMode
  id?: string
  label?: ReactNode
  className?: string
}

export default function UaRadio({
  size = 'medium',
  mode = 'normal',
  id,
  label,
  value,
  name,
  checked,
  defaultChecked,
  disabled = false,
  required = false,
  autoFocus = false,
  className,
  onChange,
  onInput,
  onFocus,
  onBlur,
  ...inputProps
}: UaRadioProps) {
  const generatedId = useId()
  const inputId = id ?? generatedId

  const wrapperClassName = ['ua-radio', size, mode, disabled ? 'disabled' : '', className]
    .filter(Boolean)
    .join(' ')

  return (
    <label className={wrapperClassName} htmlFor={inputId}>
      <input
        {...inputProps}
        id={inputId}
        className="radio-button"
        type="radio"
        value={value}
        name={name}
        checked={checked}
        defaultChecked={defaultChecked}
        disabled={disabled}
        required={required}
        autoFocus={autoFocus}
        onChange={onChange}
        onInput={onInput}
        onFocus={onFocus}
        onBlur={onBlur}
      />
      {label ? <span className="label">{label}</span> : null}
    </label>
  )
}

// system/components/vue/ua-radio/ua-radio.vue
<template>
  <label :class="classes" class="ua-radio">
    <input
      :id="props.id"
      v-model="modelValue"
      :name="props.name"
      :value="props.value"
      :checked="props.checked"
      :disabled="props.disabled"
      :required="props.required"
      :autofocus="props.autofocus"
      class="radio-button"
      type="radio"
      @change="emit('change', $event)"
      @input="emit('input', $event)"
    />
    <span v-if="props.label" class="label">{{ props.label }}</span>
  </label>
</template>

<script setup>
import { computed } from 'vue'

const modelValue = defineModel({ type: String })
const emit = defineEmits(['change', 'input'])

const props = defineProps({
  size: {
    type: String,
    required: true,
    validator: (value) => ['small', 'medium', 'large'].includes(value)
  },
  value: {
    type: String,
    required: true
  },
  name: {
    type: String
  },
  label: {
    type: String
  },
  mode: {
    type: String,
    validator: (value) => ['normal', 'reverse'].includes(value)
  },
  id: {
    type: String
  },
  checked: {
    type: Boolean
  },
  disabled: {
    type: Boolean
  },
  required: {
    type: Boolean
  },
  autofocus: {
    type: Boolean
  }
})

const classes = computed(() => {
  return {
    [props.size]: props.size,
    [props.mode]: props.mode,
    disabled: props.disabled
  }
})
</script>

<style lang="scss">
@import '../../styles/ua-radio.scss';
</style>
