// system/components/react/ua-skeleton/ua-skeleton.tsx
import type { SkeletonFormat } from '../../../types/tokens'
import '../../styles/ua-skeleton.scss'

export interface UaSkeletonProps {
  format?: SkeletonFormat
  width?: string
  height?: string
  className?: string
}

export default function UaSkeleton({
  format = 'round',
  width = '240px',
  height = '56px',
  className
}: UaSkeletonProps) {
  return (
    <div className={['ua-skeleton', format, className].filter(Boolean).join(' ')} style={{ width, height }} />
  )
}

// system/components/wc/ua-skeleton/ua-skeleton.js
import '../../styles/ua-skeleton.scss'

class UaSkeleton extends HTMLElement {
  static get observedAttributes() {
    return ['format', 'width', 'height']
  }

  connectedCallback() {
    this.render()
  }

  attributeChangedCallback() {
    this.render()
  }

  render() {
    const format = this.getAttribute('format') ?? 'round'
    const width = this.getAttribute('width') ?? '240px'
    const height = this.getAttribute('height') ?? '56px'

    this.innerHTML = `<div class="ua-skeleton ${format}" style="width: ${width}; height: ${height};"></div>`
  }
}

if (!customElements.get('ua-skeleton')) {
  customElements.define('ua-skeleton', UaSkeleton)
}

export default UaSkeleton
