// system/components/react/ua-button/ua-button.tsx
import type { ButtonHTMLAttributes, ReactNode } from 'react'
import type { BorderStyle, ButtonAppearance, Size, WidthBehavior } from '../../../types/tokens'
import '../../styles/ua-button.scss'

export interface UaButtonProps
  extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'type' | 'children'> {
  type?: 'button' | 'submit' | 'reset'
  size?: Size
  appearance?: ButtonAppearance
  widthBehavior?: WidthBehavior
  borderStyle?: BorderStyle
  leftIcon?: string
  rightIcon?: string
  children?: ReactNode
}

export default function UaButton({
  type = 'button',
  size = 'medium',
  appearance = 'primary',
  widthBehavior = 'auto',
  borderStyle = 'square',
  leftIcon,
  rightIcon,
  disabled = false,
  autoFocus = false,
  value,
  name,
  form,
  className,
  children = 'Button',
  onClick,
  ...buttonProps
}: UaButtonProps) {
  const computedClassName = ['ua-button', size, appearance, widthBehavior, borderStyle].join(' ')

  return (
    <button
      {...buttonProps}
      type={type}
      disabled={disabled}
      autoFocus={autoFocus}
      value={value}
      name={name}
      form={form}
      className={[computedClassName, className].filter(Boolean).join(' ')}
      onClick={onClick}
    >
      {leftIcon ? <span className="material-symbols-rounded icon">{leftIcon}</span> : null}
      {children ? <span className="text">{children}</span> : null}
      {rightIcon ? <span className="material-symbols-rounded icon">{rightIcon}</span> : null}
    </button>
  )
}

// system/components/vue/ua-button/ua-button.vue
<template>
  <button
    :type="props.type"
    :disabled="props.disabled"
    :autofocus="props.autofocus"
    :value="props.value"
    :name="props.name"
    :form="props.form"
    :class="buttonClasses"
    class="ua-button"
    @click="emit('click', $event)"
  >
    <span v-if="props.leftIcon" class="material-symbols-rounded icon">
      {{ props.leftIcon }}
    </span>
    <span v-if="$slots.default" class="text">
      <slot></slot>
    </span>
    <span v-if="props.rightIcon" class="material-symbols-rounded icon">
      {{ props.rightIcon }}
    </span>
  </button>
</template>

<script setup>
import { computed } from 'vue'

const emit = defineEmits(['click'])

const props = defineProps({
  type: {
    type: String,
    required: true,
    validator: (value) => ['button', 'submit', 'reset'].includes(value)
  },
  size: {
    type: String,
    required: true,
    validator: (value) => ['small', 'medium', 'large'].includes(value)
  },
  appearance: {
    type: String,
    required: true,
    validator: (value) =>
      [
        'primary',
        'secondary',
        'tertiary',
        'success',
        'warning',
        'danger',
        'informative',
        'ghost'
      ].includes(value)
  },
  widthBehavior: {
    type: String,
    default: 'auto',
    validator: (value) => ['auto', 'full'].includes(value)
  },
  borderStyle: {
    type: String,
    default: 'square',
    validator: (value) => ['round', 'square'].includes(value)
  },
  leftIcon: {
    type: String
  },
  rightIcon: {
    type: String
  },
  disabled: {
    type: Boolean
  },
  autofocus: {
    type: Boolean
  },
  value: {
    type: String
  },
  name: {
    type: String
  },
  form: {
    type: String
  }
})

const buttonClasses = computed(() => {
  return {
    [props.size]: props.size,
    [props.appearance]: props.appearance,
    [props.widthBehavior]: props.widthBehavior,
    [props.borderStyle]: props.borderStyle
  }
})
</script>

<style lang="scss">
@import '../../styles/ua-button.scss';
</style>
