// system/components/react/ua-input-text/ua-input-text.jsx
import '../../styles/ua-input-text.scss'

export default function UaInputText({
  appearance = 'neutral',
  borderStyle = 'square',
  size = 'medium',
  widthBehavior = 'auto',
  id,
  label = 'Text',
  icon,
  prefix,
  suffix,
  placeholder,
  required = false,
  disabled = false,
  readOnly = false,
  maxLength,
  minLength,
  autoComplete,
  autoCorrect,
  autoFocus = false,
  name,
  inputMode,
  pattern,
  spellCheck = false,
  value,
  onInput,
  onFocus,
  onBlur,
  onChange
}) {
  const fieldClassName = ['ua-input-text', size, appearance, widthBehavior, borderStyle].join(' ')
  const wrapperClassName = ['form-element-wrapper', disabled ? 'disabled' : ''].join(' ').trim()

  return (
    <label className={wrapperClassName}>
      <span className="label">{label}</span>
      <div className={fieldClassName}>
        {icon ? <span className="material-symbols-rounded icon">{icon}</span> : null}
        {prefix ? <span className="prefix">{prefix}</span> : null}
        <input
          id={id}
          className="field"
          type="text"
          value={value}
          placeholder={placeholder}
          required={required}
          disabled={disabled}
          readOnly={readOnly}
          maxLength={maxLength}
          minLength={minLength}
          autoComplete={autoComplete}
          autoCorrect={autoCorrect}
          autoFocus={autoFocus}
          name={name}
          inputMode={inputMode}
          pattern={pattern}
          spellCheck={spellCheck}
          onInput={onInput}
          onFocus={onFocus}
          onBlur={onBlur}
          onChange={onChange}
        />
        {suffix ? <span className="suffix">{suffix}</span> : null}
      </div>
    </label>
  )
}

// system/components/ua-input-text/ua-input-text.vue
<template>
  <label :class="wrapperClasses" class="form-element-wrapper">
    <span class="label">
      {{ props.label }}
    </span>
    <div :class="inputClasses" class="ua-input-text">
      <span v-if="props.icon" class="material-symbols-rounded icon">
        {{ props.icon }}
      </span>
      <span v-if="props.prefix" class="prefix">
        {{ props.prefix }}
      </span>
      <input
        :id="props.id"
        v-model="inputValue"
        :placeholder="props.placeholder"
        :required="props.required"
        :disabled="props.disabled"
        :readonly="props.readonly"
        :maxlength="props.maxlength"
        :minlength="props.minlength"
        :autocomplete="props.autocomplete"
        :autocorrect="props.autocorrect"
        :autofocus="props.autofocus"
        :name="props.name"
        :inputmode="props.inputmode"
        :pattern="props.pattern"
        :spellcheck="props.spellcheck"
        :class="inputClasses"
        type="text"
        class="field"
        @input="emit('input', $event)"
        @focus="emit('focus', $event)"
        @blur="emit('blur', $event)"
        @change="emit('change', $event)"
      />
      <span v-if="props.suffix" class="suffix">
        {{ props.suffix }}
      </span>
    </div>
  </label>
</template>

<script setup>
import { computed } from 'vue'

const inputValue = defineModel({ type: String })
const emit = defineEmits(['input', 'focus', 'blur', 'change'])

const props = defineProps({
  appearance: {
    type: String,
    default: 'neutral',
    validator: (value) => ['neutral', 'success', 'error'].includes(value)
  },
  borderStyle: {
    type: String,
    default: 'square',
    validator: (value) => ['round', 'square'].includes(value)
  },
  size: {
    type: String,
    required: true,
    validator: (value) => ['small', 'medium', 'large'].includes(value)
  },
  widthBehavior: {
    type: String,
    default: 'auto',
    validator: (value) => ['auto', 'full'].includes(value)
  },
  id: { type: String },
  label: { type: String },
  icon: { type: String },
  prefix: { type: String },
  suffix: { type: String },
  placeholder: { type: String },
  required: { type: Boolean },
  disabled: { type: Boolean },
  readonly: { type: Boolean },
  maxlength: { type: Number },
  minlength: { type: Number },
  autocomplete: {
    type: String,
    validator: (value) =>
      [
        'hidden',
        'text',
        'search',
        'url',
        'date',
        'month',
        'week',
        'time',
        'datetime-local',
        'number',
        'range',
        'color'
      ].includes(value)
  },
  autocorrect: { type: String, validator: (value) => ['on', 'off'].includes(value) },
  autofocus: { type: Boolean },
  name: { type: String },
  inputmode: { type: String },
  pattern: { type: String },
  spellcheck: { type: Boolean }
})

const inputClasses = computed(() => {
  return {
    [props.size]: props.size,
    [props.appearance]: props.appearance,
    [props.widthBehavior]: props.widthBehavior,
    [props.borderStyle]: props.borderStyle
  }
})

const wrapperClasses = computed(() => {
  return {
    disabled: props.disabled
  }
})
</script>

<style lang="scss">
@import './ua-input-text.scss';
</style>
