// system/components/vue/ua-toast/ua-toast.vue
<template>
  <div class="ua-toast" :class="toastClasses">
    <div class="header">
      <div class="title-wrapper">
        <span class="material-symbols-rounded icon">
          {{ toastIcon }}
        </span>
        <span class="title">
          {{ props.title }}
        </span>
      </div>
      <span class="material-symbols-rounded dismiss-icon" @click="emit('dismiss', $event)">
        close
      </span>
    </div>
    <div class="content">
      {{ props.message }}
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'

const emit = defineEmits(['dismiss'])

const props = defineProps({
  appearance: {
    type: String,
    required: true,
    validator: (value) => ['neutral', 'success', 'warning', 'danger', 'informative'].includes(value)
  },
  title: {
    type: String,
    required: true
  },
  message: {
    type: String,
    required: true
  }
})

const toastClasses = computed(() => {
  return {
    [props.appearance]: props.appearance
  }
})

const toastIcon = computed(() => {
  switch (props.appearance) {
    case 'neutral':
      return 'info'
    case 'success':
      return 'check_circle'
    case 'warning':
      return 'warning'
    case 'danger':
      return 'error'
    case 'informative':
      return 'info'
    default:
      return 'info'
  }
})
</script>

<style lang="scss">
@import '../../styles/ua-toast.scss';
</style>

// system/components/react/ua-toast/ua-toast.jsx
import '../../styles/ua-toast.scss'

const ICON_MAP = {
  neutral: 'info',
  success: 'check_circle',
  warning: 'warning',
  danger: 'error',
  informative: 'info'
}

export default function UaToast({
  appearance = 'neutral',
  title = 'Toast title',
  message = 'Toast message',
  onDismiss
}) {
  return (
    <div className={`ua-toast ${appearance}`}>
      <div className="header">
        <div className="title-wrapper">
          <span className="material-symbols-rounded icon">{ICON_MAP[appearance] ?? 'info'}</span>
          <span className="title">{title}</span>
        </div>
        <span className="material-symbols-rounded dismiss-icon" onClick={onDismiss}>
          close
        </span>
      </div>
      <div className="content">{message}</div>
    </div>
  )
}
