// system/components/wc/ua-toast/ua-toast.js
import '../../styles/ua-toast.scss'

const ICON_MAP = {
  neutral: 'info',
  success: 'check_circle',
  warning: 'warning',
  danger: 'error',
  informative: 'info'
}

class UaToast extends HTMLElement {
  static get observedAttributes() {
    return ['appearance', 'title', 'message']
  }

  connectedCallback() {
    this.render()
  }

  attributeChangedCallback() {
    this.render()
  }

  render() {
    const appearance = this.getAttribute('appearance') ?? 'neutral'
    const title = this.getAttribute('title') ?? 'Toast title'
    const message = this.getAttribute('message') ?? 'Toast message'
    const icon = ICON_MAP[appearance] ?? 'info'

    this.innerHTML = `
      <div class="ua-toast ${appearance}">
        <div class="header">
          <div class="title-wrapper">
            <span class="material-symbols-rounded icon">${icon}</span>
            <span class="title">${title}</span>
          </div>
          <span class="material-symbols-rounded dismiss-icon">close</span>
        </div>
        <div class="content">${message}</div>
      </div>
    `

    const dismiss = this.querySelector('.dismiss-icon')
    if (dismiss) {
      dismiss.addEventListener('click', (event) => {
        this.dispatchEvent(new CustomEvent('dismiss', { detail: event, bubbles: true }))
      })
    }
  }
}

if (!customElements.get('ua-toast')) {
  customElements.define('ua-toast', UaToast)
}

export default UaToast

// system/components/react/ua-toast/ua-toast.jsx
import '../../styles/ua-toast.scss'

const ICON_MAP = {
  neutral: 'info',
  success: 'check_circle',
  warning: 'warning',
  danger: 'error',
  informative: 'info'
}

export default function UaToast({
  appearance = 'neutral',
  title = 'Toast title',
  message = 'Toast message',
  onDismiss
}) {
  return (
    <div className={`ua-toast ${appearance}`}>
      <div className="header">
        <div className="title-wrapper">
          <span className="material-symbols-rounded icon">{ICON_MAP[appearance] ?? 'info'}</span>
          <span className="title">{title}</span>
        </div>
        <span className="material-symbols-rounded dismiss-icon" onClick={onDismiss}>
          close
        </span>
      </div>
      <div className="content">{message}</div>
    </div>
  )
}
