// system/components/react/ua-button/ua-button.jsx
import '../../styles/ua-button.scss'

export default function UaButton({
  type = 'button',
  size = 'medium',
  appearance = 'primary',
  widthBehavior = 'auto',
  borderStyle = 'square',
  leftIcon,
  rightIcon,
  disabled = false,
  autofocus = false,
  value,
  name,
  form,
  children = 'Button',
  onClick
}) {
  const className = ['ua-button', size, appearance, widthBehavior, borderStyle].join(' ')

  return (
    <button
      type={type}
      disabled={disabled}
      autoFocus={autofocus}
      value={value}
      name={name}
      form={form}
      className={className}
      onClick={onClick}
    >
      {leftIcon ? <span className="material-symbols-rounded icon">{leftIcon}</span> : null}
      {children ? <span className="text">{children}</span> : null}
      {rightIcon ? <span className="material-symbols-rounded icon">{rightIcon}</span> : null}
    </button>
  )
}

// system/components/wc/ua-button/ua-button.js
import '../../styles/ua-button.scss'

const boolAttr = (value) => value !== null && value !== 'false'

class UaButton extends HTMLElement {
  static get observedAttributes() {
    return [
      'type',
      'size',
      'appearance',
      'width-behavior',
      'border-style',
      'left-icon',
      'right-icon',
      'disabled',
      'autofocus',
      'value',
      'name',
      'form',
      'label'
    ]
  }

  connectedCallback() {
    this.render()
  }

  attributeChangedCallback() {
    this.render()
  }

  render() {
    const type = this.getAttribute('type') ?? 'button'
    const size = this.getAttribute('size') ?? 'medium'
    const appearance = this.getAttribute('appearance') ?? 'primary'
    const widthBehavior = this.getAttribute('width-behavior') ?? 'auto'
    const borderStyle = this.getAttribute('border-style') ?? 'square'
    const leftIcon = this.getAttribute('left-icon')
    const rightIcon = this.getAttribute('right-icon')
    const disabled = boolAttr(this.getAttribute('disabled'))
    const autofocus = boolAttr(this.getAttribute('autofocus'))
    const value = this.getAttribute('value')
    const name = this.getAttribute('name')
    const form = this.getAttribute('form')
    const label = this.getAttribute('label') ?? 'Button'

    this.innerHTML = `
      <button class="ua-button ${size} ${appearance} ${widthBehavior} ${borderStyle}" type="${type}" ${disabled ? 'disabled' : ''} ${autofocus ? 'autofocus' : ''} ${value ? `value="${value}"` : ''} ${name ? `name="${name}"` : ''} ${form ? `form="${form}"` : ''}>
        ${leftIcon ? `<span class="material-symbols-rounded icon">${leftIcon}</span>` : ''}
        <span class="text">${label}</span>
        ${rightIcon ? `<span class="material-symbols-rounded icon">${rightIcon}</span>` : ''}
      </button>
    `
  }
}

if (!customElements.get('ua-button')) {
  customElements.define('ua-button', UaButton)
}

export default UaButton
